name: Build Whitepaper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-apt-
      
    - name: Install just
      uses: extractions/setup-just@v1
      
    - name: Build LaTeX environment
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: latex-tools:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
      
    - name: Bump version
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: just bump-version
      
    - name: Build whitepaper
      run: just build
            
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: action-whitepaper
        path: action-whitepaper.pdf
        if-no-files-found: error
        compression-level: 0
